package com.nexus.saga.domain.model;

import java.util.List;

/**
 * SagaFailureExplanation — Section 3 structured output.
 *
 * Generated by gpt-4o-mini with entity(SagaFailureExplanation.class).
 * Passed to Notification Service for user-facing failure messages.
 *
 * Rules enforced in AI system prompt:
 * - Never reveal internal system names
 * - Never reveal fraud model details
 * - Always confirm funds status
 * - Always provide actionable next steps
 * - Write in user's language
 */
public record SagaFailureExplanation(
        String userFacingTitle,
        String userFacingExplanation,
        List<String> whatHappened,
        List<String> whatToDoNext,
        boolean fundsAreReleased,
        boolean canRetry,
        String retryGuidance,
        String supportReference,
        String language
) {
    /** Minimal fallback when AI generation fails */
    public static SagaFailureExplanation fallback(
            String failureType,
            boolean fundsReleased,
            boolean canRetry,
            String language) {

        boolean es = "es".equals(language);

        return new SagaFailureExplanation(
                es ? "Operación no completada"
                        : "Operation Could Not Be Completed",
                es ? "Tu operación no pudo completarse en este momento. "
                        + (fundsReleased
                        ? "Tus fondos no fueron debitados."
                        : "Por favor contacta soporte.")
                        : "Your operation could not be completed. "
                        + (fundsReleased
                        ? "No funds were debited."
                        : "Please contact support."),
                List.of(),
                List.of(es ? "Intenta de nuevo más tarde"
                        : "Try again later"),
                fundsReleased,
                canRetry,
                null,
                "REF-" + java.util.UUID.randomUUID()
                        .toString().substring(0, 8).toUpperCase(),
                language
        );
    }
}