spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/GAMER/Music/PROJECT IA STARTUP/NEXUS/nexus-config-service/nexus-platform-config
          default-label: main
          clone-on-start: false
          force-pull: false
          refresh-rate: 5
          search-paths:
            - "."
    bus:
      enabled: false

  kafka:
    bootstrap-servers: localhost:19092

  security:
    user:
      name: nexus-config
      password: nexus-config-password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  tracing:
    enabled: false

logging:
  level:
    root: INFO
    com.nexus: DEBUG
    org.springframework.cloud.config.server: DEBUG
