server:
  port: 8888

spring:
  application:
    name: nexus-config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Solano204/nexus-platform-config.git
          default-label: main
          clone-on-start: true
          force-pull: true
          refresh-rate: 30
          search-paths:
            - "."
          username: ${GIT_USERNAME:Solano204}
          password: ${GIT_TOKEN}
    bus:
      enabled: true
      refresh:
        enabled: true
      destination: spring.cloud.bus

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}

  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:nexus-config}
      password: ${CONFIG_SERVER_PASSWORD:nexus-config-password}

eureka:
  instance:
    hostname: nexus-config-service
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh,env,prometheus,monitor
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9412/api/v2/spans}

logging:
  level:
    root: INFO
    com.nexus: INFO
    org.springframework.cloud.config: INFO
