ALTER TABLE saga_timeouts
    ADD COLUMN IF NOT EXISTS timeout_type VARCHAR(50)  NOT NULL DEFAULT 'SAGA_STEP',
    ADD COLUMN IF NOT EXISTS fires_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS is_cancelled BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS fired_at     TIMESTAMPTZ;
