# ── Outputs ───────────────────────────────────────────────────────────────────
# After `terraform apply`, run:
#   terraform output -raw env_block >> .env
# to append the generated credentials to your .env file.
# ─────────────────────────────────────────────────────────────────────────────

output "env_block" {
  description = "Copy-paste this entire block into your .env file"
  sensitive   = true
  value       = <<-EOT

    # ─── AWS — generated by Terraform ────────────────────────────
    AWS_REGION=${var.aws_region}
    AWS_ENDPOINT=
    AWS_ACCESS_KEY_ID=${aws_iam_access_key.nexus_platform.id}
    # AWS_SECRET_ACCESS_KEY is never re-derivable for an imported key — keep
    # whatever value is already in your .env from when this key was first created.
    AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.nexus_platform.secret}

    # ─── Cognito (nexus-identity-service, nexus-api-gateway) ──────
    # Auth-lambda "Option B" mirror — see AWS-DOCKER-WORKFLOWS/02_LOGIN_FLOW.md
    COGNITO_USER_POOL_ID=${aws_cognito_user_pool.nexus.id}
    COGNITO_REGION=${var.aws_region}

    # ─── KYC Resources (nexus-identity-service, nexus-ai-kyc-service) ─
    KYC_S3_BUCKET=${aws_s3_bucket.kyc_documents.bucket}
    KYC_QUEUE_URL=${aws_sqs_queue.kyc_pending.url}
    KYC_SQS_QUEUE_URL=${aws_sqs_queue.kyc_pending.url}
    KYC_REKOGNITION_RESULTS_QUEUE_URL=${aws_sqs_queue.kyc_rekognition_results.url}

    # ─── Encryption (set to true once tested end-to-end) ─────────
    KYC_ENCRYPTION_ENABLED=false

    # ─── Notification dispatch (nexus-notification-service) ──────
    # Real, already-coded integration — AwsConfig.java wires a live SnsClient.
    SNS_NOTIFICATION_DISPATCH_TOPIC_ARN=${aws_sns_topic.notification_dispatch.arn}

    # ─── Fraud alerts (nexus-fraud-service) ───────────────────────
    # nexus-fraud-service's AwsConfig.java only wires an SqsClient (no SNS) —
    # SNS_FRAUD_ALERTS_TOPIC_ARN is not read anywhere in that service's code
    # yet, so it's left blank here. FRAUD_ALERTS_QUEUE_URL is the SQS queue
    # the fraud-alert Lambda actually listens on — wire fraud-service to send
    # there directly (sqs:SendMessage) once that code path is built.
    SNS_FRAUD_ALERTS_TOPIC_ARN=
    FRAUD_ALERTS_QUEUE_URL=${aws_sqs_queue.fraud_alert_high_severity.url}

    # ─── Plane bridge secret ──────────────────────────────────────
    # Lambdas send this as the X-Plane-Bridge-Secret header when calling back
    # into docker-compose. nexus-identity-service validates it on
    # /internal/v1/users/{userId}/kyc/status — this same value also needs to
    # go into nexus-identity-service's ./secrets/plane_bridge_secret.txt
    # (Docker secret file, not a plain env var — see docker-compose-prod.yml).
    # The other 3 Lambda integrations (see terraform/secrets.tf) don't
    # validate it yet.
    PLANE_BRIDGE_SECRET=${local.plane_bridge_secret_value}

  EOT
}

# ── Individual outputs for CI / scripting ────────────────────────────────────

output "aws_region" {
  description = "AWS region where resources are deployed"
  value       = var.aws_region
}

output "aws_access_key_id" {
  description = "IAM access key ID — set as AWS_ACCESS_KEY_ID"
  value       = aws_iam_access_key.nexus_platform.id
  sensitive   = true
}

output "aws_secret_access_key" {
  description = "IAM secret access key — set as AWS_SECRET_ACCESS_KEY"
  value       = aws_iam_access_key.nexus_platform.secret
  sensitive   = true
}

output "kyc_s3_bucket" {
  description = "KYC S3 bucket name — set as KYC_S3_BUCKET"
  value       = aws_s3_bucket.kyc_documents.bucket
}

output "kyc_s3_bucket_arn" {
  description = "KYC S3 bucket ARN"
  value       = aws_s3_bucket.kyc_documents.arn
}

output "kyc_queue_url" {
  description = "KYC SQS queue URL — set as KYC_QUEUE_URL and KYC_SQS_QUEUE_URL"
  value       = aws_sqs_queue.kyc_pending.url
}

output "kyc_queue_arn" {
  description = "KYC SQS queue ARN"
  value       = aws_sqs_queue.kyc_pending.arn
}

output "kyc_dlq_url" {
  description = "KYC dead-letter queue URL — for monitoring / manual replay"
  value       = aws_sqs_queue.kyc_dlq.url
}

output "kyc_dlq_arn" {
  description = "KYC dead-letter queue ARN"
  value       = aws_sqs_queue.kyc_dlq.arn
}

output "iam_user_name" {
  description = "IAM user name for the Nexus platform service account"
  value       = aws_iam_user.nexus_platform.name
}

output "iam_user_arn" {
  description = "IAM user ARN — useful for cross-account policies"
  value       = aws_iam_user.nexus_platform.arn
}
