spring:
  cloud:
    config:
      enabled: true
      fail-fast: true
      username: ${CONFIG_SERVER_USERNAME:nexus-config}
      password: ${CONFIG_SERVER_PASSWORD:nexus-config-password}
    bus:
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://nexus-discovery-service:8761/eureka/}

nexus:
  services:
    account:
      url: ${ACCOUNT_SERVICE_URL:http://nexus-account-service:8085}
    transaction:
      url: ${TRANSACTION_SERVICE_URL:http://nexus-transaction-service:8086}
    fraud:
      url: ${FRAUD_SERVICE_URL:http://nexus-fraud-service:8087}

management:
  tracing:
    enabled: true
    sampling:
      probability: 0.05
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://nexus-zipkin:9411/api/v2/spans}

logging:
  level:
    root: WARN
    com.nexus.assistant: INFO
    org.springframework.ai: WARN
    org.apache.kafka: WARN
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
