spring:
  cloud:
    config:
      enabled: true
      fail-fast: true
      username: ${CONFIG_SERVER_USERNAME:nexus-config}
      password: ${CONFIG_SERVER_PASSWORD:nexus-config-password}
    bus:
      enabled: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://nexus-discovery-service:8761/eureka/}

management:
  tracing:
    enabled: true
    sampling:
      probability: 0.05
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://nexus-zipkin:9411/api/v2/spans}

logging:
  level:
    root: WARN
    com.nexus.risk: INFO
    org.hibernate.SQL: WARN
    org.apache.kafka: WARN
    org.springframework.ai: WARN
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
