apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://nexus-prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://nexus-loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"([a-f0-9]+)"'
          url: http://localhost:9411/zipkin/traces/$${__value.raw}
          urlDisplayLabel: Open in Zipkin
        - name: UserID
          matcherRegex: '"userId":"([^"]+)"'
          url: ""
          urlDisplayLabel: Filter by user
