apiVersion: 1

datasources:
  - name: Prometheus
    uid: nexus-prometheus
    type: prometheus
    access: proxy
    url: http://nexus-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: nexus-loki
    type: loki
    access: proxy
    url: http://nexus-loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceId":"([a-f0-9]+)"'
          url: http://localhost:9414/zipkin/traces/$${__value.raw}
          urlDisplayLabel: Open in Zipkin
        - name: UserID
          matcherRegex: '"userId":"([^"]+)"'
          url: ""
          urlDisplayLabel: Filter by user
