package com.nexus.payment.lambda.model.enums;


public enum FailureReason {
    NONE,
    MISSING_REQUIRED_FIELD,
    INVALID_AMOUNT,
    UNKNOWN_CARD_TOKEN,
    ACCOUNT_NOT_FOUND,
    DUPLICATE_EVENT,
    KAFKA_BRIDGE_UNAVAILABLE,
    KAFKA_BRIDGE_TIMEOUT,
    SNS_PUBLISH_FAILED,
    SCHEMA_VALIDATION_ERROR,
    ENRICHMENT_FAILED,
    INTERNAL_ERROR
}