package com.nexus.audit.write.model;

import io.quarkus.runtime.annotations.RegisterForReflection;

import java.time.Instant;

/**
 * Compliance Alert — generated by real-time rule evaluation.
 *
 * Rules:
 * - VELOCITY_ANOMALY: 5+ transactions in 5 minutes
 * - LARGE_TRANSACTION: amount > MXN 10,000
 * - HIGH_FRAUD_SCORE: fraudScore > 70
 * - POTENTIAL_STRUCTURING: 3+ sub-threshold txns in 7 days
 * - CRITICAL_EVENT: account freeze, document fraud
 *
 * Stored in MongoDB compliance_alerts collection.
 * Reviewed by compliance team via JVM query path.
 */
@RegisterForReflection
public record ComplianceAlert(
        String alertId,
        String alertType,
        String severity,
        String userId,
        String triggeringEventId,
        String description,
        String regulatoryReference,
        boolean sarConsideration,
        Instant generatedAt,
        boolean reviewed
) {
    public static ComplianceAlertBuilder builder() {
        return new ComplianceAlertBuilder();
    }

    public static class ComplianceAlertBuilder {
        private String alertId;
        private String alertType;
        private String severity;
        private String userId;
        private String triggeringEventId;
        private String description;
        private String regulatoryReference;
        private boolean sarConsideration;
        private Instant generatedAt;

        public ComplianceAlertBuilder alertId(String v) { this.alertId = v; return this; }
        public ComplianceAlertBuilder alertType(String v) { this.alertType = v; return this; }
        public ComplianceAlertBuilder severity(String v) { this.severity = v; return this; }
        public ComplianceAlertBuilder userId(String v) { this.userId = v; return this; }
        public ComplianceAlertBuilder triggeringEventId(String v) { this.triggeringEventId = v; return this; }
        public ComplianceAlertBuilder description(String v) { this.description = v; return this; }
        public ComplianceAlertBuilder regulatoryReference(String v) { this.regulatoryReference = v; return this; }
        public ComplianceAlertBuilder sarConsideration(boolean v) { this.sarConsideration = v; return this; }
        public ComplianceAlertBuilder generatedAt(Instant v) { this.generatedAt = v; return this; }

        public ComplianceAlert build() {
            return new ComplianceAlert(alertId, alertType, severity, userId,
                    triggeringEventId, description, regulatoryReference,
                    sarConsideration, generatedAt, false);
        }
    }
}