spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:nexus}:${MONGO_PASSWORD}@${MONGO_HOST:nexus-mongodb}:27017/nexus_notification?authSource=admin
    redis:
      host: ${REDIS_HOST:nexus-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
