spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:nexus-postgres}:5432/nexus_transactions
    username: ${POSTGRES_USER:nexus}
    password: ${POSTGRES_PASSWORD}
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:nexus-elasticsearch}:9200
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:nexus-kafka:9092}
    streams:
      state-dir: /var/kafka-streams/transaction
