spring:
  data:
    redis:
      host: ${REDIS_HOST:nexus-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

nexus:
  gateway:
    jwt:
      public-key-url: http://${IDENTITY_SERVICE_HOST:nexus-identity-service}:8083/api/v1/auth/.well-known/jwks.json
