spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nexus_transactions
    username: nexus
    password: nexus_dev_password
  elasticsearch:
    uris: http://localhost:9201
  kafka:
    streams:
      state-dir: /tmp/kafka-streams/transaction
