spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:nexus-postgres}:5432/nexus_kyc
    username: ${POSTGRES_USER:nexus}
    password: ${POSTGRES_PASSWORD}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:nexus}:${MONGO_PASSWORD}@${MONGO_HOST:nexus-mongodb}:27017/nexus_kyc?authSource=admin
