spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_transaction
    username: nexus
    password: nexus_dev_password
  data:
    elasticsearch:
      uris: http://localhost:9200
  kafka:
    streams:
      state-dir: /tmp/kafka-streams/transaction
