spring:
  data:
    elasticsearch:
      uris: http://localhost:9201
    redis:
      host: localhost
      port: 6380
      password: ""
  kafka:
    streams:
      state-dir: /tmp/kafka-streams/analytics
